Description: A middleware stack that adds a new hostname with its own target group to an Ether Cattle Load Balancer.

Parameters:
  InfrastructureStack:
    Type: String
    Description: The infrastructure stack this target group extends
  HostedZone:
    Type: String
    Description: Route53 hosted zone for DNS
  ServiceName:
    Type: String
    Description: The name for this service (DNS will be ServiceName.HostedZone)
  Priority:
    Type: Number
    Default: 1
    Description: The listener rule priority for this stack. Must be a unique number for children of the parent.


Resources:
  RPCALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      Actions:
      - Type: forward
        TargetGroupArn: !Ref RPCALBGroup
      Conditions:
      - Field: host-header
        Values:
        - !Sub "${ServiceName}.${HostedZone}"
      ListenerArn:
        "Fn::ImportValue":
          !Sub "${InfrastructureStack}-RPCALBListener"
      Priority: !Ref Priority
  RPCALBGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 30
      UnhealthyThresholdCount: 2
      HealthyThresholdCount: 5
      Port: 8545
      Protocol: HTTP
      VpcId:
        "Fn::ImportValue":
            !Sub "${InfrastructureStack}-VpcId"
  RPCALBDNS:
    Type: "AWS::Route53::RecordSet"
    Properties:
      AliasTarget:
        DNSName:
          "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBDNS"
        EvaluateTargetHealth: False
        HostedZoneId:
          "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBCanonicalHostedZoneId"
      HostedZoneName: !Sub "${HostedZone}."
      Name: !Sub "${ServiceName}.${HostedZone}"
      Type: A


Outputs:
  ClusterId:
    Description: The cluster ID
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-ClusterId"
    Export:
      Name: !Sub "${AWS::StackName}-ClusterId"
  RPCALBGroup:
    Description: The ARN of the alb target group for the RPC load balancer
    Value: !Ref RPCALBGroup
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBGroup"
  RPCALBGroupName:
    Description: The full name of the alb target group for the RPC load balancer
    Value: !Sub ${RPCALBGroup.TargetGroupFullName}
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBGroupName"
  RPCALBName:
    Description: The full name of the RPC load balancer
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBName"
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBName"
  RPCALBDNS:
    Description: The DNS of the RPC load balancer
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBDNS"
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBDNS"
  RPCALBListener:
    Description: The ARN of the RPC load balancer's listener
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBListener"
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBListener"
  RPCALBCanonicalHostedZoneId:
    Description: The ALB's Canonical hosted zone
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-RPCALBCanonicalHostedZoneId"
    Export:
      Name: !Sub "${AWS::StackName}-RPCALBCanonicalHostedZoneId"
  VpcId:
    Description: The VPC the stack is deployed to
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-VpcId"
    Export:
      Name: !Sub "${AWS::StackName}-VpcId"
  VpcBaseIp:
    Description: The VpcBaseIp the stack is deployed to
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-VpcBaseIp"
    Export:
      Name: !Sub "${AWS::StackName}-VpcBaseIp"
  Kafka2HostnameA:
    Description: The Kafka hostname for AZ 'a'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-Kafka2HostnameA"
    Export:
      Name: !Sub "${AWS::StackName}-Kafka2HostnameA"
  Kafka2HostnameB:
    Description: The Kafka hostname for AZ 'b'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-Kafka2HostnameB"
    Export:
      Name: !Sub "${AWS::StackName}-Kafka2HostnameB"
  Kafka2HostnameC:
    Description: The Kafka hostname for AZ 'c'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-Kafka2HostnameC"
    Export:
      Name: !Sub "${AWS::StackName}-Kafka2HostnameC"
  PublicA:
    Description: The Subnet in availability zone 'a'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PublicA"
    Export:
      Name: !Sub "${AWS::StackName}-PublicA"
  PublicB:
    Description: The Subnet in availability zone 'b'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PublicB"
    Export:
      Name: !Sub "${AWS::StackName}-PublicB"
  PublicC:
    Description: The Subnet in availability zone 'c'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PublicC"
    Export:
      Name: !Sub "${AWS::StackName}-PublicC"
  PrivateA:
    Description: The Subnet in availability zone 'a'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PrivateA"
    Export:
      Name: !Sub "${AWS::StackName}-PrivateA"
  PrivateB:
    Description: The Subnet in availability zone 'b'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PrivateB"
    Export:
      Name: !Sub "${AWS::StackName}-PrivateB"
  PrivateC:
    Description: The Subnet in availability zone 'c'
    Value:
      "Fn::ImportValue": !Sub "${InfrastructureStack}-PrivateC"
    Export:
      Name: !Sub "${AWS::StackName}-PrivateC"
